# Generated by Django 4.2.3 on 2023-07-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_userprofile_is_reviewer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("", "Select Role"),
                    ("is_translator", "Translator"),
                    ("is_reviewer", "Reviewer"),
                ],
                default=("", "Select Role"),
                max_length=100,
            ),
        ),
    ]
