# Generated by Django 4.2.3 on 2023-08-06 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_userprofile_role"),
        ("translator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextToTranslate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("english", "english"),
                            ("Igbo", "Igbo"),
                            ("Yoruba", "Yoruba"),
                            ("Hausa", "Hausa"),
                        ],
                        default="english",
                        max_length=100,
                    ),
                ),
                ("translation", models.TextField()),
                (
                    "totranslate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="translator.texttotranslate",
                    ),
                ),
                (
                    "translator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.userprofile",
                    ),
                ),
            ],
        ),
    ]
