# Generated by Django 4.2.3 on 2023-09-22 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("translator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ViewTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review", models.IntegerField(default=0)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="translator.translation",
                    ),
                ),
            ],
        ),
    ]
